// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSArZRaZywOmMzv5FwFQ6kqBdmogtXM-U',
    appId: '1:298346869636:web:a6aae25d3807e582a123d1',
    messagingSenderId: '298346869636',
    projectId: 'mediation-express',
    authDomain: 'mediation-express.firebaseapp.com',
    storageBucket: 'mediation-express.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc7u3M1LKRlKKko9c45sKrq9cP_A7t1LU',
    appId: '1:298346869636:android:606b5d0d017fc12fa123d1',
    messagingSenderId: '298346869636',
    projectId: 'mediation-express',
    storageBucket: 'mediation-express.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXFNyRm3uxFrPzkH-vBUYQjq3lSnbLsgw',
    appId: '1:298346869636:ios:3cb33a5951899ed9a123d1',
    messagingSenderId: '298346869636',
    projectId: 'mediation-express',
    storageBucket: 'mediation-express.firebasestorage.app',
    iosBundleId: 'com.example.mediationExpress',
  );
}
